# Generated by Django 5.0 on 2023-12-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='bio',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='pet',
            name='profile_img',
            field=models.URLField(max_length=600),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.URLField(max_length=1000),
        ),
    ]
