# Generated by Django 5.0 on 2023-12-13 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_pet_profile_img_alter_post_post_image'),
        ('pets', '0003_pet_bio_alter_pet_profile_img_alter_post_post_image'),
    ]

    operations = [
    ]
